# Kết nối SQL Server (Bổ sung thêm sendStringParametersAsUnicode=true để hết lỗi font từ gốc)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PharmacyChainDB_Student;sendStringParametersAsUnicode=true;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ép kiểu UTF-8 cho HTTP (Dùng chuẩn server.servlet cho Spring Boot 3)
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Ép kiểu UTF-8 cho Thymeleaf
spring.thymeleaf.encoding=UTF-8