spring.application.name=PharmacyManagement
server.port=8080

spring.messages.encoding=UTF-8

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PharmacyChainDB_Student;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none

spring.data.jpa.repositories.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.thymeleaf.cache=false

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
